### ISSUE TITLE
possible replication of first frame in large datasets on Intel integrated GPU

### ISSUE THREAD

**Issue by tlambert03** [napari/napari#1507]
## 🐛 Bug
from  https://forum.image.sc/t/napari-stuck-view-in-3d-cube/40899/4

I haven't had time to try to reproduce this yet, but @kapoorlab is seeing a strange issue in which the first timepoint of a relatively large (82, 65, 967, 516) 4D volume is superimposed on all later timepoints.  If he crops Z to ~16 planes, it seems to go away.

**Comment by kapoorlab** [comment]
Here is an example dataset to try this:

https://drive.google.com/file/d/1qqXiGunUN3ecpR5j8K4QIz2_196-cVU1/view?usp=sharing

**Comment by tlambert03** [comment]
Thanks,  I tried to recreate with synthetic data but it didn't happen:

```python
import numpy as np
import napari

shape = (82, 65, 967, 516)
data = np.ones(shape)
for i in range(len(data)):
    start = 50+5*i
    strip = slice(start, start + 7)
    data[i,:,:,strip] = 3

with napari.gui_qt():
    viewer = napari.view_image(data, rgb=False, scale=[1, 1, 0.16, 0.16], contrast_limits=(0, 3))
```

so I'll take a look at this dataset

**Comment by tlambert03** [comment]
hmm... i also couldn't see it with your dataset, though I opened it with `napari path/to/file.tif` instead of using imread...  Could you 1) paste the output of your `napari --info` here ... and 2) give me more details on the imread?  is that from skimage?  tifffile?

**Comment by tlambert03** [comment]
also, just want to double check that you tested this smaller dataset `shape = (10, 27, 967, 516)` and definitely still see it?

**Comment by kapoorlab** [comment]
My napari --info output:

`
napari: 0.3.6
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.17.2
VisPy: 0.6.4

GL version:  2.1 INTEL-12.10.12
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.5
  - svg: 0.1.3
`

I see this problem for small dataset also, but it goes away if I choose Z = 16. Changing Image dtype from uint8 to float16 also does not help. 
imread is from tifffile but I also tried it from skimage and same result as from tifffile. I have not tried to load dataset using napari  /path/to/file.tif though.

**Comment by sofroniewn** [comment]
Ok, wow this one is a surprise!!

Cross-posting my comment from image.sc - i'm curious if you drop the scale arg do weird things still happen?

Curious if you go back in time before https://github.com/napari/napari/pull/1445 then do bad things still happen?

**Comment by kapoorlab** [comment]
Hi, yeah there is one more surprise I noticed but first, I went back in time n cloned the dev repo, napari info for that:
`
(base) AIMachines-MacBook-Pro:napari aimachine$ napari --info
napari: 0.1.dev768+g9b90648
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.18.4
SciPy: 1.4.1
Dask: 2.5.2
VisPy: 0.6.4

GL version:  2.1 INTEL-12.10.12
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.6
  - svg: 0.1.3
`
No scale set, just drag n drop the image and choose the cube and same error as wee see it now. Also setting scale or unsetting it does not help, it is still showing the same bug with no scaling set in the view_mage.

Now the next surprise, If I want to edit labels on the image and put the scale keyword inn the view_image napari does not allow me to draw or edit labels, only turning it off lets me edit labels. But that seems to be a feature than a bug right? So I did not point it out before but just mentioning it in the passing.

**Comment by sofroniewn** [comment]
> If I want to edit labels on the image and put the scale keyword inn the view_image napari does not allow me to draw or edit labels, only turning it off lets me edit labels. But that seems to be a feature than a bug right?

maybe, but probably something that should be fixed, can you make a dedicated issue for this one

**Comment by Czaki** [comment]
> Now the next surprise, If I want to edit labels on the image and put the scale keyword inn the view_image napari does not allow me to draw or edit labels, only turning it off lets me edit labels. But that seems to be a feature than a bug right? So I did not point it out before but just mentioning it in the passing.

could You try if for code from this PR this problem is fixed? https://github.com/napari/napari/pull/1360
It may be connected with wrong handling scale when creating labels. 
I meet this problem on other side of scale (large values) in #1407 

It is partially fixed (for your case also should be).

**Comment by kapoorlab** [comment]
Hi @Czaki ,

I tried the PR #1360 but it does not solve the issue because scaling does not seem to cause this problem. Even with no scaling the problem remains.

**Comment by Czaki** [comment]
Could you provide information about RAM in your computer?
Could you describe steps?

Did You have access to other computer and could reproduce any of these two bugs?

**Comment by kapoorlab** [comment]
@Czaki I am using a standard Macbook pro. I open a Jupyter notebook where the images are tiff files of about 3 GB and read using imread and then I launch napari gui from the notebook and switch to the cube view and I see this error. Even drag n drop in napari would cause the same issue.

Maybe you can try the dataset I uploaded and see if you see the same error as me?

**Comment by Czaki** [comment]
@kapoorlab 
I try this on Ubuntu and on MacOS (MacBook Pro (Retina, 15-inch, Mid 2015) 16 GB RAM). And not see this error. 
Only difference which I see is that I use pure CPython (from pyenv) and You use Python from Anaconda. 

I could paint on labels (it work only in 2D mode). And first layer does replicate. 

I think that You need to provide more information to allow other person to reproduce this problem. I may be details as laptop model. graphic card etc. 
```
napari: 0.3.6
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.6.9 (default, May 7 2020, 20:21:55) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.21.0
VisPy: 0.6.4

GL version: 2.1 ATI-2.11.21
MAX_TEXTURE_SIZE: 16384

Plugins:
- napari_plugin_engine: 0.1.7
- svg: 0.1.3
```

**Comment by kapoorlab** [comment]
My Napari info is as follows:

napari: 0.3.6
Platform: Darwin-18.7.0-x86_64-i386-64bit
Python: 3.7.3 (default, Mar 27 2019, 16:54:48)  [Clang 4.0.1 (tags/RELEASE_401/final)]
Qt: 5.14.2
PyQt5: 5.14.2
NumPy: 1.19.1
SciPy: 1.5.2
Dask: 2.21.0
VisPy: 0.6.4

GL version:  2.1 INTEL-12.10.12
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari-plugin-engine: 0.1.6
  - svg: 0.1.3

Maybe it is my plugin engine which has a version lower? 

My Macbook Pro 14,2 info:
 Processor Name:	Intel Core i7
 Memory:	16 GB

**Comment by Czaki** [comment]
Hm. In this moment I have no idea. I cannot reproduce this bug. Maybe someone else will have better idea.

**Comment by tlambert03** [comment]
@kapoorlab, can you
- try loading data with `napari path/to/image.tif` and see if it still happens for you?
- provide a full script with imports showing how the data is loaded
- try my synthetic example above and see if it happens for you

**Comment by kapoorlab** [comment]
@tlambert03 

So I tried loading data with napari path/to/image.tif and it still happens.

My script:

`
import os
from tifffile import imread
import napari


ImageName = '/Users/aimachine/Downloads/C2-Raw_Timelapse_87E_Tomato_GFP.tif'

scaleX = 0.161
scaleY = 0.161
scaleZ = 1

Name = os.path.basename(os.path.splitext(ImageName)[0])
Image = imread(ImageName)
Image= Image.astype('float16')
print(Image.dtype)
with napari.gui_qt():
    print(Image.shape)
    viewer = napari.view_image(Image, name='Raw', rgb=False) 
`

With the synthetic image also it happens, see my screenshots here:
[Synthetic example](https://forum.image.sc/t/napari-stuck-view-in-3d-cube/40899/6?u=kapoorlab)

So something is wrong locally on my system it seems.

**Comment by tlambert03** [comment]
> So something is wrong locally on my system it seems.

yep, I'm coming to the same conclusion... but it's still quite interesting.  I'd like to try to recreate it locally... can you do `conda list --export > requirements.txt` and upload the file here?  And if you have time, create a fresh conda environment and see if the problem persists?

**Comment by kapoorlab** [comment]
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
_anaconda_depends=2019.03=py37_0
alabaster=0.7.12=py37_0
anaconda=custom=py37_1
anaconda-client=1.7.2=py37_0
anaconda-project=0.8.3=py_0
appdirs=1.4.3=pypi_0
appnope=0.1.0=pypi_0
appscript=1.1.0=py37h1de35cc_0
asciitree=0.3.3=pypi_0
asn1crypto=0.24.0=py37_0
astroid=2.3.1=py37_0
astropy=3.2.1=py37h1de35cc_0
atomicwrites=1.3.0=py37_1
attrs=19.2.0=py_0
babel=2.8.0=pypi_0
backcall=0.2.0=pypi_0
backports=1.0=py_2
backports.os=0.1.1=py37_0
backports.shutil_get_terminal_size=1.0.0=py37_2
beautifulsoup4=4.8.0=py37_0
bitarray=1.0.1=py37h1de35cc_0
bkcharts=0.2=py37_0
blas=1.0=mkl
bleach=3.1.0=py37_0
blosc=1.16.3=hd9629dc_0
bokeh=1.3.4=py37_0
boto=2.49.0=py37_0
bottleneck=1.2.1=py37h1d22016_1
btrack=0.3.8=pypi_0
bzip2=1.0.8=h1de35cc_0
ca-certificates=2020.1.1=0
cachey=0.2.1=pypi_0
certifi=2020.6.20=pypi_0
cffi=1.12.3=py37hb5b8e2f_0
chardet=3.0.4=py37_1003
click=7.0=py37_0
cloudpickle=1.2.2=py_0
clyent=1.2.2=py37_1
colorama=0.4.1=py37_0
conda=4.8.3=py37_0
conda-package-handling=1.6.0=py37h1de35cc_0
contextlib2=0.6.0=py_0
cryptography=2.7=py37ha12b0ac_0
csbdeep=0.5.1=pypi_0
curl=7.65.3=ha441bb4_0
cvxopt=1.2.5=pypi_0
cycler=0.10.0=pypi_0
cython=0.29.13=py37h0a44026_0
cytoolz=0.10.0=py37h1de35cc_0
dask=2.21.0=pypi_0
dask-core=2.5.2=py_0
dbus=1.13.6=h90a0687_0
decorator=4.4.2=pypi_0
defusedxml=0.6.0=py_0
distlib=0.3.0=pypi_0
distributed=2.5.2=py_0
docutils=0.16=pypi_0
entrypoints=0.3=py37_0
et_xmlfile=1.0.1=py37_0
expat=2.2.6=h0a44026_0
fastcache=1.1.0=py37h1de35cc_0
fasteners=0.15=pypi_0
filelock=3.0.12=py_0
flask=1.1.1=py_0
freetype=2.9.1=hb4e5f40_0
freetype-py=2.2.0=pypi_0
fsspec=0.5.2=py_0
get_terminal_size=1.0.0=h7520d66_0
gettext=0.19.8.1=h15daf44_3
gevent=1.4.0=py37h1de35cc_0
glib=2.56.2=hd9629dc_0
glob2=0.7=py_0
gmp=6.1.2=hb37e062_1
gmpy2=2.0.8=py37h6ef4df4_2
greenlet=0.4.15=py37h1de35cc_0
h5py=2.10.0=pypi_0
hdf5=1.10.4=hfa1e0ec_0
heapdict=1.0.1=py_0
html5lib=1.0.1=py37_0
icu=58.2=h4b95b61_1
idna=2.10=pypi_0
imagecodecs=2020.2.18=pypi_0
imageio=2.9.0=pypi_0
imagesize=1.2.0=pypi_0
importlib-metadata=1.7.0=pypi_0
intel-openmp=2019.4=233
ipykernel=5.3.4=pypi_0
ipython=7.16.1=pypi_0
ipython-genutils=0.2.0=pypi_0
ipython_genutils=0.2.0=py37_0
ipywidgets=7.5.1=py_0
isort=4.3.21=py37_0
itsdangerous=1.1.0=py37_0
jbig=2.1=h4d881f8_0
jdcal=1.4.1=py_0
jedi=0.17.2=pypi_0
jinja2=2.11.2=pypi_0
joblib=0.13.2=py37_0
jpeg=9b=he5867d9_2
json5=0.8.5=py_0
jsonschema=3.0.2=py37_0
jupyter=1.0.0=py37_7
jupyter-client=6.1.6=pypi_0
jupyter-core=4.6.3=pypi_0
jupyter_client=5.3.3=py37_1
jupyter_console=6.0.0=py37_0
jupyter_core=4.5.0=py_0
jupyterlab=1.1.4=pyhf63ae98_0
jupyterlab_server=1.0.6=py_0
keras=2.3.1=pypi_0
keras-applications=1.0.8=pypi_0
keras-preprocessing=1.1.2=pypi_0
keyring=18.0.0=py37_0
kiwisolver=1.2.0=pypi_0
krb5=1.16.1=hddcf347_7
labelme=3.16.7=pypi_0
lazy-object-proxy=1.4.2=py37h1de35cc_0
libarchive=3.3.3=h786848e_5
libcurl=7.65.3=h051b688_0
libcxx=4.0.1=hcfea43d_1
libcxxabi=4.0.1=hcfea43d_1
libedit=3.1.20181209=hb402a30_0
libffi=3.2.1=h475c297_4
libgfortran=3.0.1=h93005f0_2
libiconv=1.15=hdd342a3_7
liblief=0.9.0=h2a1bed3_2
libpng=1.6.37=ha441bb4_0
libsodium=1.0.16=h3efe00b_0
libssh2=1.8.2=ha12b0ac_0
libtiff=4.0.10=hcb84e12_2
libxml2=2.9.9=hf6e021a_1
libxslt=1.1.33=h33a18ac_0
llvm-openmp=4.0.1=hcfea43d_1
llvmlite=0.32.1=pypi_0
locket=0.2.0=py37_1
lxml=4.4.1=py37hef8c89e_0
lz4-c=1.8.1.2=h1de35cc_0
lzo=2.10=h362108e_2
markupsafe=1.1.1=py37h1de35cc_0
matplotlib=3.2.1=pypi_0
mccabe=0.6.1=py37_1
mistune=0.8.4=py37h1de35cc_0
mkl=2019.4=233
mkl-service=2.3.0=py37hfbe908c_0
mkl_fft=1.0.14=py37h5e564d8_0
mkl_random=1.1.0=py37ha771720_0
mock=3.0.5=py37_0
monotonic=1.5=pypi_0
more-itertools=7.2.0=py37_0
mpc=1.1.0=h6ef4df4_1
mpfr=4.0.1=h3018a27_3
mpmath=1.1.0=py37_0
msgpack-python=0.6.1=py37h04f5b5a_1
multipledispatch=0.6.0=py37_0
napari=0.3.6=pypi_0
napari-plugin-engine=0.1.6=pypi_0
napari-svg=0.1.3=pypi_0
nb_conda=2.2.1=py37_0
nb_conda_kernels=2.2.2=py37_0
nbconvert=5.6.0=py37_1
nbformat=4.4.0=py37_0
ncurses=6.1=h0a44026_1
networkx=2.4=pypi_0
nltk=3.4.5=py37_0
nose=1.3.7=py37_2
notebook=6.0.1=py37_0
numba=0.49.1=pypi_0
numcodecs=0.6.3=pypi_0
numexpr=2.7.0=py37h7413580_0
numpy=1.19.1=pypi_0
numpy-base=1.17.2=py37h6575580_0
numpydoc=1.1.0=pypi_0
olefile=0.46=py37_0
ont=1.0.0=pypi_0
opencv-python=4.2.0.32=pypi_0
openpyxl=3.0.0=py_0
openssl=1.1.1g=h1de35cc_0
packaging=20.4=pypi_0
pandas=0.25.1=py37h0a44026_0
pandoc=2.2.3.2=0
pandocfilters=1.4.2=py37_1
parso=0.7.1=pypi_0
partd=1.0.0=py_0
path.py=12.0.1=py_0
pathlib2=2.3.5=py37_0
patsy=0.5.1=py37_0
pcre=8.43=h0a44026_0
pep8=1.7.1=py37_0
pexpect=4.8.0=pypi_0
phantomjs=2.1.1=1
pickleshare=0.7.5=pypi_0
pillow=7.1.2=pypi_0
pip=19.2.3=py37_0
pipenv=2018.11.26=pypi_0
pkginfo=1.5.0.1=py37_0
pluggy=0.13.0=py37_0
ply=3.11=py37_0
prometheus_client=0.7.1=py_0
prompt-toolkit=3.0.5=pypi_0
prompt_toolkit=2.0.10=py_0
psutil=5.7.2=pypi_0
ptyprocess=0.6.0=pypi_0
py=1.8.0=py37_0
py-lief=0.9.0=py37h1413db1_2
pycodestyle=2.5.0=py37_0
pycosat=0.6.3=py37h1de35cc_0
pycparser=2.19=py37_0
pycrypto=2.6.1=py37h1de35cc_9
pycurl=7.43.0.3=py37ha12b0ac_0
pyflakes=2.1.1=py37_0
pygments=2.6.1=pypi_0
pylint=2.4.2=py37_0
pyodbc=4.0.27=py37h0a44026_0
pyopengl=3.1.5=pypi_0
pyopenssl=19.0.0=py37_0
pyparsing=2.4.7=pypi_0
pyqt=5.9.2=py37h655552a_2
pyqt5=5.14.2=pypi_0
pyqt5-sip=12.8.0=pypi_0
pyrsistent=0.15.4=py37h1de35cc_0
pyside2=5.13.2=pypi_0
pysocks=1.7.1=py37_0
pytables=3.5.2=py37h5bccee9_1
pytest=5.2.1=py37_0
pytest-arraydiff=0.3=py37h39e3cac_0
pytest-astropy=0.5.0=py37_0
pytest-doctestplus=0.4.0=py_0
pytest-openfiles=0.4.0=py_0
pytest-remotedata=0.3.2=py37_0
python=3.7.3=h359304d_0
python-dateutil=2.8.1=pypi_0
python-libarchive-c=2.8=py37_13
python.app=2=py37_9
pytz=2020.1=pypi_0
pywavelets=1.1.1=pypi_0
pyyaml=5.3.1=pypi_0
pyzmq=19.0.1=pypi_0
qt=5.9.7=h468cd18_1
qtawesome=0.6.0=py_0
qtconsole=4.7.5=pypi_0
qtpy=1.9.0=py_0
read-roi=1.5.2=pypi_0
readline=7.0=h1de35cc_5
requests=2.24.0=pypi_0
rope=0.14.0=py_0
ruamel_yaml=0.15.46=py37h1de35cc_0
scikit-image=0.17.2=pypi_0
scikit-learn=0.21.3=py37h27c97d8_0
scipy=1.5.2=pypi_0
seaborn=0.9.0=py37_0
selenium=3.141.0=py37h1de35cc_0
send2trash=1.5.0=py37_0
setuptools=49.2.0=pypi_0
shiboken2=5.13.2=pypi_0
simplegeneric=0.8.1=py37_2
singledispatch=3.4.0.3=py37_0
sip=4.19.8=py37h0a44026_0
six=1.15.0=pypi_0
sklearn=0.0=pypi_0
snappy=1.1.7=he62c110_3
snowballstemmer=2.0.0=py_0
sortedcollections=1.1.2=py37_0
sortedcontainers=2.1.0=py37_0
soupsieve=1.9.3=py37_0
sphinx=3.1.2=pypi_0
sphinxcontrib=1.0=py37_1
sphinxcontrib-applehelp=1.0.2=pypi_0
sphinxcontrib-devhelp=1.0.2=pypi_0
sphinxcontrib-htmlhelp=1.0.3=pypi_0
sphinxcontrib-jsmath=1.0.1=py_0
sphinxcontrib-qthelp=1.0.3=pypi_0
sphinxcontrib-serializinghtml=1.1.4=pypi_0
sphinxcontrib-websupport=1.1.2=py_0
spyder=3.3.6=py37_0
spyder-kernels=0.5.2=py37_0
sqlalchemy=1.3.9=py37h1de35cc_0
sqlite=3.30.0=ha441bb4_0
stardist=0.5.0=pypi_0
statsmodels=0.10.1=py37h1d22016_0
sympy=1.4=py37_0
tbb=2019.4=h04f5b5a_0
tblib=1.4.0=py_0
termcolor=1.1.0=pypi_0
terminado=0.8.2=py37_0
testpath=0.4.2=py37_0
tifffile=2020.7.24=pypi_0
tiffile=2018.10.18=pypi_0
tk=8.6.8=ha441bb4_0
toolz=0.10.0=py_0
tornado=6.0.4=pypi_0
tqdm=4.46.0=pypi_0
traitlets=4.3.3=py37_0
unicodecsv=0.14.1=py37_0
unixodbc=2.3.7=h1de35cc_0
urllib3=1.25.10=pypi_0
virtualenv=20.0.18=pypi_0
virtualenv-clone=0.5.4=pypi_0
vispy=0.6.4=pypi_0
wcwidth=0.2.5=pypi_0
webencodings=0.5.1=py37_1
werkzeug=0.16.0=py_0
wheel=0.33.6=py37_0
widgetsnbextension=3.5.1=py37_0
wrapt=1.12.1=pypi_0
wurlitzer=1.0.3=py37_0
xlrd=1.2.0=py37_0
xlsxwriter=1.2.1=py_0
xlwings=0.15.10=py37_0
xlwt=1.3.0=py37_0
xz=5.2.4=h1de35cc_4
yaml=0.1.7=hc338f04_2
zarr=2.3.2=pypi_0
zeromq=4.3.1=h0a44026_3
zict=1.0.0=py_0
zipp=3.1.0=pypi_0
zlib=1.2.11=h1de35cc_3
zstd=1.3.7=h5bba6e5_0

```

**Comment by kapoorlab** [comment]
I created a new minimal environment with fresh install of napari and still napari path/to/.tif gives me the same error. The requirements file for this environment contains:
```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
alabaster=0.7.12=pypi_0
appnope=0.1.0=pypi_0
babel=2.8.0=pypi_0
backcall=0.2.0=pypi_0
ca-certificates=2020.6.24=0
cachey=0.2.1=pypi_0
certifi=2020.6.20=py36_0
chardet=3.0.4=pypi_0
dask=2.21.0=pypi_0
decorator=4.4.2=pypi_0
docutils=0.16=pypi_0
freetype-py=2.2.0=pypi_0
heapdict=1.0.1=pypi_0
idna=2.10=pypi_0
imageio=2.9.0=pypi_0
imagesize=1.2.0=pypi_0
importlib-metadata=1.7.0=pypi_0
ipykernel=5.3.4=pypi_0
ipython=7.16.1=pypi_0
ipython-genutils=0.2.0=pypi_0
jedi=0.17.2=pypi_0
jinja2=2.11.2=pypi_0
jupyter-client=6.1.6=pypi_0
jupyter-core=4.6.3=pypi_0
libcxx=10.0.0=1
libedit=3.1.20191231=h1de35cc_1
libffi=3.3=hb1e8313_2
markupsafe=1.1.1=pypi_0
napari=0.3.6=pypi_0
napari-plugin-engine=0.1.7=pypi_0
napari-svg=0.1.3=pypi_0
ncurses=6.2=h0a44026_1
numpy=1.19.1=pypi_0
numpydoc=1.1.0=pypi_0
openssl=1.1.1g=h1de35cc_0
packaging=20.4=pypi_0
parso=0.7.1=pypi_0
pexpect=4.8.0=pypi_0
pickleshare=0.7.5=pypi_0
pillow=7.2.0=pypi_0
pip=20.1.1=py36_1
prompt-toolkit=3.0.5=pypi_0
psutil=5.7.2=pypi_0
ptyprocess=0.6.0=pypi_0
pygments=2.6.1=pypi_0
pyopengl=3.1.5=pypi_0
pyparsing=2.4.7=pypi_0
pyqt5=5.14.2=pypi_0
pyqt5-sip=12.8.0=pypi_0
python=3.6.10=hf48f09d_2
python-dateutil=2.8.1=pypi_0
pytz=2020.1=pypi_0
pyyaml=5.3.1=pypi_0
pyzmq=19.0.1=pypi_0
qtconsole=4.7.5=pypi_0
qtpy=1.9.0=pypi_0
readline=8.0=h1de35cc_0
requests=2.24.0=pypi_0
scipy=1.5.2=pypi_0
setuptools=49.2.0=py36_0
six=1.15.0=pypi_0
snowballstemmer=2.0.0=pypi_0
sphinx=3.1.2=pypi_0
sphinxcontrib-applehelp=1.0.2=pypi_0
sphinxcontrib-devhelp=1.0.2=pypi_0
sphinxcontrib-htmlhelp=1.0.3=pypi_0
sphinxcontrib-jsmath=1.0.1=pypi_0
sphinxcontrib-qthelp=1.0.3=pypi_0
sphinxcontrib-serializinghtml=1.1.4=pypi_0
sqlite=3.32.3=hffcf06c_0
tifffile=2020.7.24=pypi_0
tk=8.6.10=hb0a8c7a_0
toolz=0.10.0=pypi_0
tornado=6.0.4=pypi_0
traitlets=4.3.3=pypi_0
urllib3=1.25.10=pypi_0
vispy=0.6.4=pypi_0
wcwidth=0.2.5=pypi_0
wheel=0.34.2=py36_0
wrapt=1.12.1=pypi_0
xz=5.2.5=h1de35cc_0
zipp=3.1.0=pypi_0
zlib=1.2.11=h1de35cc_3
```

**Comment by tlambert03** [comment]
> I created a new minimal environment with fresh install of napari and still napari path/to/.tif gives me the same error.

wow.  well I just tried both environments, and I _still_ can't reproduce it here locally... and I double checked to make sure the environments are the same.  so I fear that means we now need to consider things like opengl drivers/platforms... which is harder (for me at least) to debug.  The only other thing I might try on your end is an environment with python3.8

**Comment by Czaki** [comment]
OpenGL could connected with replication, but I cannot imageine how it could be connected with label editing.

**Comment by kapoorlab** [comment]
I also tried python3.8 environment, still the same bug for me!

**Comment by Czaki** [comment]
Did you have possibility to get access to other computer and test on it?

**Comment by kapoorlab** [comment]
Not at the moment, am on holidays but will do that as soon as I am back in the office.

**Comment by kapoorlab** [comment]
Hello, I can confirm that the issue only shows up on my Mac and not on the more powerful computer that I have. On my mac I still see the stuck view but for the same image/program running on server/powerful computer with >60 GB of RAM the issue does not exist.

**Comment by Czaki** [comment]
Maybe it is some OpenGL bug in your driver

**Comment by sofroniewn** [comment]
Hi all, sounds like this bug ended up being fairly hardware specific/ possibly openGL / memory related. I'll leave this open for a couple more days in case anyone can shed any further light on this and then I will close it. Sorry we couldn't get to the bottom of it @kapoorlab! Thanks for reporting it

**Comment by kapoorlab** [comment]
https://github.com/napari/napari/issues/1393#issuecomment-745615931

I am on the current python 3.9.0 napari testenv and I still have the sticky issue till now, it is just not going away. My current napari info in this enviornment:

`
napari: 0.4.2
Platform: macOS-10.16-x86_64-i386-64bit
Python: 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:54:06)  [Clang 11.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.2
NumPy: 1.19.4
SciPy: 1.5.4
Dask: 2020.12.0
VisPy: 0.6.6

GL version:  2.1 INTEL-16.0.49
MAX_TEXTURE_SIZE: 16384

Plugins:
  - napari_plugin_engine: 0.1.8
  - svg: 0.1.4
`
 OS: Mac OS Sur
Graphics driver : Intel Iris Plus Graphics 650

**Comment by sofroniewn** [comment]
@kapoorlab can you test pyside2, we've been having some pyqt5 only related problems when lots of memory is being used

**Comment by kapoorlab** [comment]
@sofroniewn I just did and it has the same behaviour as pyqt5. If I open ZT view it works fine with dragging either Z or T slider but as soon as I switch to the cube view and drag the slider the first frame (pyside2) sticks over the others.

**Comment by jni** [comment]
You might see on the link above @kapoorlab that the issue happened to @sofroniewn when we were developing the I2K tutorial. He "fixed" it by downscaling the image. Not much of a fix but a clue at least! It might be interesting, for example, to see if it happens to more people given large enough volumes...

**Comment by kapoorlab** [comment]
Ah the issue is still alive I just reproduced it in  python 3.9.7 on a Mac for image of dimensions: (74, 22, 973, 512)

**Comment by sofroniewn** [comment]
> Ah the issue is still alive I just reproduced it in python 3.9.7 on a Mac for image of dimensions: (74, 22, 973, 512)

Thanks for the bump. Maybe @nclack can try digging into this one at some point in time. It seems to be hardware specific. It would probably be good to figure out if this can be reproduced with vispy only. @AhmetCanSolak might have ideas too as I think he might have seen some other memory leaks in the past too

**Comment by nclack** [comment]
I very briefly looked at this. I suspect there's a gl failure somewhere along the line. Is there a way to turn on gl error checking? 

Setting
```
vispy.util.config['gl_debug']=True
```

nominally enables checking for errors after each gl call; errors are silently ignored normally.  However, I'm not able to reproduce the problem and I can't confirm the above actually turned on the error checking :)

**Comment by perlman** [comment]
(Apologies if this is a red herring...)

This issue feels very similar to one with neuroglancer (https://github.com/google/neuroglancer/issues/51), in which the first layer of each chunk would be replicated, but _only_ on computers with Intel integrated video (e.g., any 13/14" Intel  MacBook Pro, but not the Intel MacBookPro 15/16" or desktop with discrete graphics -- consistent with what I've seen in this issue.)

This was related to OpenGL SL allowing division to be replaced by multiplication of the reciprocal.
@jbms has a much more complete description [here](https://github.com/google/neuroglancer/issues/51#issuecomment-332979697).

**Comment by jbms** [comment]
There have certainly been a lot of GPU-specific bugs in Neuroglancer related to floating point precision issues.  However, I don't know enough about how napari implements rendering to say whether there is likely to be any conneciton.  If napari renders from 3-d or higher-d textures/buffers stored in GPU memory, then I think it is possible there is a similar issue.  If napari renders from 2-d textures/buffers in GPU memory, then it is less likely to be a similar issue.

**Comment by kapoorlab** [comment]
@nclack thanks for the tip, I tried it but it did not show errors, I think what @perlman is pointing out is the case here as this only happens on my Mac of 14" and not on my linux workstation. Well I will just buy a new laptop with linux as it seems to be the easiest solution :).

**Comment by AhmetCanSolak** [comment]
Late to the party but I am able to reproduce the problem with synthetic data(haven't tried the original dataset yet) on an intel mac BigSur 11.6. I went through the discussion here but also there seems to be multiple image.sc threads on this issue. Anyone has the whole picture on where we are at debugging this? So I can take it over from there and debug this.

I already tried @nclack 's `vispy.util.config['gl_debug']=True` suggestion but I am not getting any gl error. @tlambert03 @nclack @sofroniewn @jni @Czaki any of you working on this?

![Screen Shot 2022-05-03 at 2 48 04 PM](https://user-images.githubusercontent.com/15677695/166572135-4aaca252-9c29-487f-8adb-beb7227a0aef.png)

**Comment by nclack** [comment]
I'm so glad you can reproduce @AhmetCanSolak. I never got very far. I initially thought it might be memory related, but my guess now is that it has something to do with the raycasting shader in vispy.  It could be that there's not enough precision somewhere...something is causing that first frame to be sampled for every frame. That's pure speculation though.

**Comment by perlman** [comment]
@AhmetCanSolak I'd be curious to see the synthetic example.

**Comment by sofroniewn** [comment]
This happened to me again last week. @perlman I can reproduce this with

```python
import napari
import dask.array as da


data = da.random.random((2, 200, 200, 200)) # Get error
# data = da.random.random((2, 100, 100, 100)) # Works fine

viewer = napari.Viewer()
layer = viewer.add_image(data)
```

entering 3D rendering mode and toggling between the first two frames. Note the smaller dataset works fine.

I'm running on macbook pro. If you are fine on both just go up to 300, 400 etc. Let me know if you cannot reproduce, i can add videos too

I would be huge @perlman if you could get to bottom of this!!!!

**Comment by tlambert03** [comment]
Huh, does it have to be dask?  Have we already narrowed this to dask?

**Comment by AhmetCanSolak** [comment]
> Huh, does it have to be dask? Have we already narrowed this to dask?

no @tlambert03 , it can be observed with numpy too.

**Comment by tlambert03** [comment]
@sofroniewn If you replace your dask script with numpy you also see it?

**Comment by sofroniewn** [comment]
> @sofroniewn If you replace your dask script with numpy you also see it?

yup! same behaviour with numpy!! sorry, i was modifying a "real" example I had that happened to be using dask

**Comment by perlman** [comment]
> I'm running on macbook pro.

intel or arm64? intel or discrete video?

I am unable to reproduce this on macOS+arm64, but I *can* reproduce on macOS+intel+integrated video.

Has anyone seen this with anything other than Intel graphics?

Also, I found it a lot easier to see (in 3D) by assigning a different color to each frame:
```python
data[0,:,:,:] = 0.75
data[1,:,:,:] = 0.25
```

![image](https://user-images.githubusercontent.com/671841/179658422-f28e397d-4112-4431-ad49-db7b57204753.png)

(@sofroniewn I have an idea for a very small tweak to the vispy volume rendering, but it'll have to wait until tomorrow.)

**Comment by sofroniewn** [comment]
<img width="314" alt="image" src="https://user-images.githubusercontent.com/6531703/179661061-a4bc53b2-f811-4f2c-a464-0709dd5b6d9a.png">

**Comment by perlman** [comment]
Well, my efforts to tweak the shader to sample with a very minor offset had no effect.

Stepping through the code, on change of `t` (the one slider in 3d view), an entirely new 3D texture is being loaded with the expected values [e.g., vol is equal to `data[0,:,:,:]` or `data[1,:,:,:]`). Thus, I'm even more confused that we get a bizarre rendering only at t=0.

[Edit: I have not actually verified that the loaded texture is correct! Just that the input to VolumeVisual is. The artifacts are only visible if t=0 and t=1 have different values.]

@brisvag Can you think of why the slider (and associated dims object) would have an effect on how `VolumeVisual` renders? I feel like I must be missing something obvious.

**Comment by brisvag** [comment]
I'm a bit lost, late to the party. If I understand correctly, If I run this code:

```py
import napari
import numpy as np

data = np.zeros((2, 200, 200, 200)) # Works fine
data[0,:,:,:] = 0.75
data[1,:,:,:] = 0.25

viewer = napari.Viewer()
layer = viewer.add_image(data, contrast_limits=(0, 1))
```

I'm supposed to see... Something strange like the stripy artifacts from @perlman? Everything looks fine on my machine.

```yaml
napari: 0.4.16rc2.dev161+g66ffffc2
Platform: Linux-5.18.12-arch1-1-x86_64-with-glibc2.35
System: Arch Linux
Python: 3.10.5 (main, Jun 6 2022, 18:49:26) [GCC 12.1.0]
Qt: 5.15.2
PyQt5: 5.15.6
NumPy: 1.22.4
SciPy: 1.8.1
Dask: 2022.6.0
VisPy: 0.10.0

OpenGL:
- GL version: 4.6.0 NVIDIA 515.57
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 1.0
- screen 2: resolution 1200x1920, scale 1.0
- screen 3: resolution 1920x1080, scale 1.0
```

**Comment by brisvag** [comment]
One thing that this reminds me of is this other time when @alisterburt saw a different behaviour from mine on his mac (can't recall what it was exactly atm), and it turned out to be caused by different *initialization* in shader code depending on the platform. Basically, doing:

```glsl
vec3 thing;
```

instead of 

```glsl
vec3 thing = some_sane_initial_value;
```

Was resulting in inconsistent behaviour depending on the platflorm, because one was all zeros and one was ones, or random, or something like that.

**Comment by perlman** [comment]
@brisvag In addition to running the code, you'd need to switch to 3D mode, rotate the volume a bit, and toggle layers. But, I wouldn't expect you to see anything odd with NVIDIA graphics. This seems to occur on Intel integrated graphics only.

> One thing that this reminds me of is this other time when @alisterburt saw a different behaviour from mine on his mac (can't recall what it was exactly atm), and it turned out to be caused by different initialization in shader code depending on the platform.

I could see that being an issue here. I'll skim through the volume shader code to see if anything looks fishy.

**Comment by psobolewskiPhD** [comment]
Anyone have an intel mac with integrated graphics to see if this is still an issue?
Maybe @andy-sweet ?
Upside is, those macs are getting long in the tooth so should be less and less common?

**Comment by andy-sweet** [comment]
> Anyone have an intel mac with integrated graphics to see if this is still an issue?
> Maybe @andy-sweet ?

I just tried [the example that @brisvag posted](https://github.com/napari/napari/issues/1507#issuecomment-1190025133) at 3596cfc8e2b6f2cf2464d6c0f795c5707eb87d68 in my napari dev environment and I didn't see any issues. Here's my full environment.

```
(napari-dev-pyqt5) ➜  napari git:(main) napari --info
napari: 0.5.0a2.dev379+g3596cfc8e
Platform: macOS-10.16-x86_64-i386-64bit
System: MacOS 13.6
Python: 3.9.6 (default, Jul 30 2021, 09:31:09)  [Clang 10.0.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.25.1
SciPy: 1.10.1
Dask: 2023.6.1
VisPy: 0.14.1
magicgui: 0.7.3
superqt: 0.5.3
in-n-out: 0.1.5
app-model: 0.2.2
npe2: 0.7.2

OpenGL:
  - GL version:  2.1 INTEL-20.6.4
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 3440x1440, scale 1.0
  - screen 2: resolution 1440x900, scale 2.0
```

> Upside is, those macs are getting long in the tooth so should be less and less common?

Hey! Compared to my personal mac (late 2013), this thing is practically a baby!

**Comment by psobolewskiPhD** [comment]
0.5.0 is released so I'm going to close. If this pops up again on Intel macs, we can reopen.
