### ISSUE TITLE
Enable per-label visibility control for labels layer

### ISSUE THREAD

**Issue by qizhuli** [napari/napari#1516]
## 🚀 Feature
The requested feature is for the labels layer to have a fine-grained visibility control for individual label values, which enables users to focus on certain label values by turning the rest invisible.

## Motivation
Often labels image can have a large number of labels. To make things worse, one label can have bits and pieces scattered in different parts of an image. These two factors can make inspecting and understanding a label image quite difficult at times. 

An example of a complex label image:
![image](https://user-images.githubusercontent.com/15232694/89121625-4d0d2700-d4b8-11ea-93d8-b31919d4127f.png)

My work involves inspecting and analysing such label images. As a workaround, I have been parsing my label images, generating further `N` label images corresponding to `N` labels in the image, and adding all these `N+1` label images to the viewer. But it is inefficient, and creates a lot of clutter in the user interface -- especially when `N` is large.

## Pitch
Therefore, it would be desirable to build in a control mechanism for labels layer that allows the users to turn on/off the visibility of certain label values in a labels image, while keeping the label colours unaffected.

**Comment by sofroniewn** [comment]
This is a great feature request! I wonder in the short term if a better workaround might involve the new `properties` dictionary added to the labels layer and the ability to use custom colormaps. See this example here https://github.com/napari/napari/blob/master/examples/add_labels_with_properties.py Maybe @DragaDoncila can also give some suggestions.

I'm curious how that goes, we can then think if there are things we could do to make the processes simpler. @hectormz has also been working on labels lately and might have some ideas too!

**Comment by DragaDoncila** [comment]
This seems like a fairly key feature for working with labels. I would say the `properties` dictionary could be leveraged to enable/disable visibility based on the values of the properties or the value of the label itself e.g. show all labels with a particular classification.

In terms of working with existing features, one option I can think of (which is certainly suboptimal), is to use the custom colormap to assign colours only to labels which exhibit a particular property. Using the [coins example](https://github.com/napari/napari/blob/master/examples/add_labels_with_properties.py), line 46 could be replaced by 

```
small_coin_indices = list(np.where(coin_sizes == 'small')[0])
color = dict(zip(
        small_coin_indices,
        ['white' for i in range(len(small_coin_indices))]
    ))
```
to colour all small coins white.

In terms of toggling individual labels though, especially through the viewer which would be ideal, I think that needs to be implemented, perhaps by adding a `visible` property which could be manipulated both based on the value of other properties, and individually.

I'm thinking a dropdown which allows you to select a category, and then has checkboxes for each value of that category. Again using the coin example, we could have a dropdown which allows for the selection of 'row' or 'size', and then checkboxes would toggle the visibility of 'top' or 'bottom' row or both, etc.

For individual labels I feel like this should be a context menu. When the label is selected (or perhaps a right click?), the user should have the option to make the label invisible or make all others labels invisible.

**Comment by qizhuli** [comment]
@DragaDoncila they are great ideas! @sofroniewn Thanks so much for supporting this feature request. 

In addition, to facilitate _systematic_ inspection through all existing label values, it would be nice to have a list of label IDs, where users can directly toggle their visibility, without having to locate them in the image. It can be implemented as an expandable menu -- which is hidden by default -- nested under the labels layer. When the user expands the menu, it shows all the label values in the layer, and a visibility toggle for each value. 

It could be something like this:

![napari](https://user-images.githubusercontent.com/15232694/89322593-57781e00-d67c-11ea-8732-48e0e979ebae.png)

**Comment by sofroniewn** [comment]
Thanks for that cool mock @qizhuli!

@tlambert03 has actually been thinking about some functionality to support layer groups that might look like that - see some discussion in #970 and #1089, but I think for changing the visibility status or name for an individual label we might want to leverage more of a properties table approach (something that we've been discussing in the context of Points with @kevinyamauchi). I think there a couple different approaches and something we might want to discuss with @liaprins-czi from a design standpoint too

**Comment by psobolewskiPhD** [comment]
I think this is addressed by `show selected` check box?
This permits inspecting labels one-at-a-time, using either the `label` `-`/`+` or entering a value, or by using the dropper/pick-mode tool.
E.g. using the Balls 3D example:

<img width="1203" alt="Image" src="https://github.com/user-attachments/assets/ca275c73-cfe5-42b9-bc72-d5ee3ec62546" />

**Comment by jni** [comment]
I agree that this is partially solved. In some scenarios, one might want to view multiple layers together. This would be enabled by multi-selection, which has been on our to-do for a while. However, #2978 was closed without making a corresponding issue. I've now created #8027 to specifically track multiple selection in Labels layers, so we can close this. 🙏
