### ISSUE TITLE
#1694 breaks statistical code analysis tool 

### ISSUE THREAD

**Issue by Czaki** [napari/napari#1713]
## 🐛 Bug

The changes introduced in #1694 really nice reduce code repetition, but break tools which base on statistical code analysis.  

![obraz](https://user-images.githubusercontent.com/3826210/95561078-7bf4cb80-0a1a-11eb-8c40-a731d9843709.png)

Also other tools (like vscode with python plugin) does not show documentation for function.

## To Reproduce

Open some of example in PyCharm editor or in vscode with python plugin (Ctrl+I, ctrl+K) . 

## Expected behavior

Basic function of napari (adding layers with napari module or viewer object) should be easy to use with whole support from code completion and showing docstring.

## Environment

 - Please copy and paste the information at napari info option in help menubar here:

 - Any other relevant information:

## Additional context

Posiible solution of this problem:

* use stub files (*.pyi)
* use assigment, like namedtuple, instead of for loop,
* instead of runtime generation generate *.py files like in resources case.

**Comment by sofroniewn** [comment]
> Posiible solution of this problem:
>
> - use stub files (*.pyi)
> - use assigment, like namedtuple, instead of for loop,
> - instead of runtime generation generate *.py files like in resources case.

Thanks for these proposed solutions @Czaki. I'm wondering if @jni or @kne42 have any recommendations or thoughts on which might be best to try first?

**Comment by tlambert03** [comment]
I believe this is solved by  the stubs that now ship with napari, but let me know if not!

**Comment by Czaki** [comment]
@tlambert03 It was still not solved. For example usage of Array class https://github.com/napari/napari/blob/c53f34e85c4fa4e2a767521ea7304cb735fa0c4d/napari/utils/events/custom_types.py#L24 
cause that tools expect given subclass of the array. I will look to check if it could be solved using `.pyi` files but please open again.

**Comment by tlambert03** [comment]
This issue was about solving the problem that dynamic method generation caused.  That issue has been solved with the stubs.  If you're saying the array class isn't perfect, that feels like a different issue entirely.  Do you have an actionable "todo" with a concrete example?
