### ISSUE TITLE
Viewer console not working when running under ipython

### ISSUE THREAD

**Issue by alisterburt** [napari/napari#2904]
## 🐛 Bug

If I run napari from an ipython console with the `%gui qt` magic then I can't access the ipython console from the viewer. Running from python rather than ipython, the console works as expected

## To Reproduce
The following opens a viewer, the error is produced when trying to access the console from the viewer
```Python
(base) ➜  napari git:(master) ✗ conda activate napari
(napari) ➜  napari git:(master) ✗ ipython
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt

In [2]: %run examples/add_image.py

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/Programming/napari/napari/utils/action_manager.py in <lambda>()
     52     def callable(self, context):
     53         if not hasattr(self, '_command_with_context'):
---> 54             self._command_with_context = lambda: call_with_context(
     55                 self.command, context
     56             )

~/Programming/napari/napari/utils/action_manager.py in call_with_context(function, context)
     41     ]
     42     ctx = {k: v for k, v in context.items() if k in context_keys}
---> 43     return function(**ctx)
     44 
     45 

~/Programming/napari/napari/_qt/qt_viewer.py in toggle_console_visibility(self, event)
    724         """
    725         # force instantiation of console if not already instantiated
--> 726         _ = self.console
    727 
    728         viz = not self.dockConsole.isVisible()

AttributeError: 'QtViewer' object has no attribute 'console'
```

The following works fine
```sh
(napari) ➜  napari git:(master) ✗ python examples/add_image.py 
```

This used to work fine on my system, not sure exactly when it broke... will have to do some searching

`napari --info`
```yaml
napari: 0.4.10.dev0+g609fd9f4.d20210623
Platform: macOS-11.2.1-x86_64-i386-64bit
System: MacOS 11.2.1
Python: 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35)  [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.6.6

OpenGL:
  - GL version:  2.1 Metal - 71.0.7
  - MAX_TEXTURE_SIZE: 16384

Screens:
  - screen 1: resolution 1440x900, scale 2.0

Plugins:
  - console: 0.0.3
  - scikit-image: 0.4.10.dev0+g609fd9f4.d20210623
  - svg: 0.1.5

```

**Comment by tlambert03** [comment]
hmm, can't reproduce on master.  but your error looks a lot like what was fixed in https://github.com/napari/napari/pull/2881 

have you pulled master recently?

**Comment by alisterburt** [comment]
hmmm, looks like I was a bit behind - I'm no longer getting the error but the console still isn't working
```bash
(base) ➜  napari git:(master) ✗ git pull upstream master
From github.com:napari/napari
 * branch              master     -> FETCH_HEAD
Already up to date.
(base) ➜  napari git:(master) ✗ conda activate napari
(napari) ➜  napari git:(master) ✗ ipython
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt

In [2]: %run examples/add_image.py
```
![image](https://user-images.githubusercontent.com/7307488/123018197-096c2600-d3c6-11eb-98a3-c5335fe2ecab.png)

edit: should clarify - no errors at all but no visible console either

**Comment by tlambert03** [comment]
I don't recall the builtin console ever working when running in ipython?

If you checkout an older version did it work?

**Comment by alisterburt** [comment]
really? I seem to remember playing with variables from both the ipython console and the builtin console but I could be mistaken, will go back and test tomorrow

The reason this has come up is now that all of the examples are using `napari.run()` when I run them from pycharm with an ipython console the event loop blocks but I also don't have the builtin console, this definitely used to work

The way pycharm launches an ipython console and runs a file is definitely non-standard though, I created my example with ipython directly in an attempt to keep things a bit simpler...
```python
/opt/homebrew/Caskroom/miniforge/base/envs/napari/bin/python /Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevconsole.py --mode=client --port=54923
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/Users/aburt/Programming/napari', '/Users/aburt/Playground/visualise_particles', '/Users/aburt/Programming/vispy'])
%gui qt
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.24.1 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 7.24.1
Python 3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:27:35) 
[Clang 11.1.0 ] on darwin
runfile('/Users/aburt/Programming/napari/examples/add_image.py', wdir='/Users/aburt/Programming/napari/examples')
```

**Comment by alisterburt** [comment]
went back to 0.4.4 and still broken - looks like you're right @tlambert03 !

**Comment by tlambert03** [comment]
I know there's been some discussion somewhere about disabling that button when running via ipython. still a good idea...

As for pycharm, I'll need to play with it (don't have much experience with it).  Maybe we can screen share for that?

**Comment by brisvag** [comment]
Console indeed never worked from IPython! It was one of the reasons why I was interested in doing #2378.
