### ISSUE TITLE
Shift with line tool prevents next lines from free adjustment

### ISSUE THREAD

**Issue by psobolewskiPhD** [napari/napari#3228]
## 🐛 Bug

Pressing shift *while using the line tool with a line started* fixes the current angle, both for the current line as well as *future* lines.
I instinctively hit shift to get a vertical or horizontal line, which is typical behavior in other drawing programs, so this bug gets me really often.

## To Reproduce

1. Create shape layer
2. Start a line using line tool
3. Press shift
4. Try rotating line. Result: only reflects, no free rotation.
5. Finish the line. 
6. Start a new line. Result: same angle, only reflections, no free rotation.

Also triggers a traceback:
<details>
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 520, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 572, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 484, in on_key_press
    self.press_key(combo)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 444, in press_key
    next(gen)  # call function
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_key_bindings.py", line 42, in hold_to_lock_aspect_ratio
    _move(layer, layer._moving_coordinates)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in _move
    coord = [coordinates[i] for i in layer._dims_displayed]
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in <listcomp>
    coord = [coordinates[i] for i in layer._dims_displayed]
TypeError: 'NoneType' object is not subscriptable
</details>

Note: I've learned that "normal" behavior can be restored by deleting the shapes layer OR by pressing shift *before* starting to draw a line, drawing the line and releasing shift.

## Expected behavior

I expected the line to be drawn fixed at 90 degree angles—vertical or horizontal—based on typical behavior in other programs. 
At the very least, I think that the shift first then draw line or line first then shift behavior should be identical. 
At the same time, to me the the current napari shift-first-then-line behavior, which yields 45 degree angles is odd, because I rarely want to draw something at that angle. Would prefer the typical vertical/horizontal behavior.

## Environment

napari: 0.4.10
Platform: macOS-11.5.2-arm64-arm-64bit
System: MacOS 11.5.2
Python: 3.9.6 | packaged by conda-forge | (default, Jul 6 2021, 08:51:19) [Clang 11.1.0 ]
Qt: 5.15.2
PyQt5: 5.15.4
NumPy: 1.21.0
SciPy: 1.7.0
Dask: 2021.06.2
VisPy: 0.7.0

OpenGL:
- GL version: 2.1 Metal - 71.7.1
- MAX_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1680x1050, scale 2.0

Plugins:
- 3 Utilities: 0.1.4
- 4 Measurements (skimage): 0.1.4
- Measurements (Plot profile): 0.1.3
- StarDist: 2021.6.28
- aicsimageio-in-memory: 0.3.5
- aicsimageio-out-of-memory: 0.3.5
- animation: 0.0.2
- clEsperanto: 0.9.10
- console: 0.0.3
- ome-types: 0.2.6
- scikit-image: 0.4.10
- svg: 0.1.5
-

**Comment by psobolewskiPhD** [comment]
Wowza, I get bizarre shift behavior with circle and rectangle tools as well:
pressing shift before drawing the shape results in circle/square, but releasing shift before ending the shape makes it 'explode' to a seemingly arbitrary, but much larger ellipse/rectangle.
Start drawing shape first, then press shift—my typical behavior—results in flashing and unpredictable behavior, with again very large ellipse/rectangle.
Edit: this may be related to the line tool traceback, because I can't reproduce the flashing and unpredictable behavior in fresh napari. Just the inability to draw circle/square if I start drawing before hitting shift.

**Comment by Carreau** [comment]
Can you try to reproduce with IPython from either the 7.x or master branch ? There was some issues that would swallow tracebacks, and it may be that some error were silenced.

I can reproduce weird behavior  as well, but with the latest of IPython I actually get notifications that something went wrong, 
in particular
```
File ~/dev/napari/napari/layers/shapes/_shapes_mouse_bindings.py, in <listcomp>(.0=<list_iterator object>)
    368 vertex = layer._moving_value[1]
    370 if layer._mode in (
    371     [Mode.SELECT, Mode.ADD_RECTANGLE, Mode.ADD_ELLIPSE, Mode.ADD_LINE]
    372 ):
--> 373     coord = [coordinates[i] for i in layer._dims_displayed]
        coordinates = None
        i = 0
    374     layer._is_moving = True
    375     if vertex is None:
    376         # Check where dragging box from to move whole object
TypeError: 'NoneType' object is not subscriptable
```

**Comment by psobolewskiPhD** [comment]
Still occurs with:
```
Python 3.9.6 | packaged by conda-forge | (default, Jul  6 2021, 08:51:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.25.0 -- An enhanced Interactive Python. Type '?' for help.
```
(previous was with the VS Code Interactive Python window)
Here's what's printed in the ipython window when drawing some lines (bugged and not bugged).
<details>
<pre>
shapes.py (2217): divide by zero encountered in true_divide
shapes.py (2217): divide by zero encountered in true_divide
vispy_camera.py (109): divide by zero encountered in true_divide
shapes.py (2217): divide by zero encountered in true_divide
shapes.py (2217): divide by zero encountered in true_divide
Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 520, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 572, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 484, in on_key_press
    self.press_key(combo)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 444, in press_key
    next(gen)  # call function
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_key_bindings.py", line 42, in hold_to_lock_aspect_ratio
    _move(layer, layer._moving_coordinates)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in _move
    coord = [coordinates[i] for i in layer._dims_displayed]
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in <listcomp>
    coord = [coordinates[i] for i in layer._dims_displayed]
TypeError: 'NoneType' object is not subscriptable

If you suspect this is an IPython 7.25.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 520, in keyPressEvent
    self._keyEvent(self._vispy_canvas.events.key_press, ev)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 572, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 484, in on_key_press
    self.press_key(combo)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 444, in press_key
    next(gen)  # call function
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_key_bindings.py", line 42, in hold_to_lock_aspect_ratio
    _move(layer, layer._moving_coordinates)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in _move
    coord = [coordinates[i] for i in layer._dims_displayed]
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in <listcomp>
    coord = [coordinates[i] for i in layer._dims_displayed]
TypeError: 'NoneType' object is not subscriptable

If you suspect this is an IPython 7.25.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

Traceback (most recent call last):
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 523, in keyReleaseEvent
    self._keyEvent(self._vispy_canvas.events.key_release, ev)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 572, in _keyEvent
    func(native=ev, key=key, text=str(ev.text()), modifiers=mod)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 453, in __call__
    self._invoke_callback(cb, event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/vispy/util/event.py", line 469, in _invoke_callback
    cb(event)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 501, in on_key_release
    self.release_key(combo)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/utils/key_bindings.py", line 461, in release_key
    next(self._key_release_generators[key])  # call function
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_key_bindings.py", line 49, in hold_to_lock_aspect_ratio
    _move(layer, layer._moving_coordinates)
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in _move
    coord = [coordinates[i] for i in layer._dims_displayed]
  File "/Users/piotrsobolewski/Dev/miniforge3/envs/TF-StarDist-napari/lib/python3.9/site-packages/napari/layers/shapes/_shapes_mouse_bindings.py", line 362, in <listcomp>
    coord = [coordinates[i] for i in layer._dims_displayed]
TypeError: 'NoneType' object is not subscriptable

If you suspect this is an IPython 7.25.0 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True
</pre>
</details>

**Comment by Carreau** [comment]
Yeah, that confirms the issue I have here. If you run napari on it's own with older version of IPython it might just swallow tracebacks.

I've narrowed it down to `layer._moving_coordinates` being None even if `_is_moving` is True, though I'm not too familiar with that part of the code base. It also seem to call into "Keep aspect ratio", so I'm not 100% sure this is only for 45º/90º lines, but at least it's a consistent error.

**Comment by sofroniewn** [comment]
I think it might just be that I implemented the wrong this here so to speak - i.e. holding shift right now locks aspect ratio - but better behaviour would be to lock to horizontal or vertical. We should probably change that. Also the error isn't great, but i don't think this behaviour ever "worked"

**Comment by Carreau** [comment]
Please see #3259 it does not fix things, but make it less broken, where at least the "keep aspect ratio" will go away of let go of shift.

**Comment by psobolewskiPhD** [comment]
Going to bump this, still a major source of irritation for me. After looking at the code a bit:
I think the issue is that when using the Select tool, shift *should* do constrain aspect ratio. This is typical of every program I've ever used that has some sort of resizable shape/thing.
This works.
But when drawing new line/oval/rect, I expect shift to trigger: horizontal/vertical line, circle, square.
This does not work in any intuitive way.

So the question is: are tool specific keybinds possible? I guess in the function currently decorated with the keybind to shift, one could check for the active tool?

**Comment by Czaki** [comment]
> But when drawing new line/oval/rect, I expect shift to trigger: horizontal/vertical line, circle, square. This does not work in any intuitive way.
> 
> So the question is: are tool specific keybinds possible? I guess in the function currently decorated with the keybind to shift, one could check for the active tool?

What I got from reading code. 
If you press Shift before start drawing Rect or Oval then you will get Square or Circle respectively. If you press it during drawing it will keep ratio of existing shape. 

This function only toggle `_fixed_aspect` flag and set `_aspect_ratio`. Whole logic is in drawing tool. 

I think that some change of this logic is a good option for 0.5.0 release.
