### ISSUE TITLE
napari doesn't start on windows 2021 Server R2

### ISSUE THREAD

**Issue by bpavie** [napari/napari#4562]
## 🐛 Bug

Start napari on a windows server 2021 Server R2

## To Reproduce

Run the following code:

```
import napari

with napari.gui_qt():
    viewer = napari.Viewer()
```

## Expected behavior

Should start napari

## Additional context

This problem is fixed by editing the ``darknet/__init__.py`` file:
Add the following test to avoid the int conversion error of the 

```
elif platform.release() == "2012ServerR2":
    from ._dummy import *
```

See the full code edited:
```
#-----------------------------------------------------------------------------
#  Copyright (C) 2019 Alberto Sottile
#
#  Distributed under the terms of the 3-clause BSD License.
#-----------------------------------------------------------------------------

__version__ = '0.5.2'

import sys
import platform

if sys.platform == "darwin":
    from distutils.version import LooseVersion as V
    if V(platform.mac_ver()[0]) < V("10.14"):
        from ._dummy import *
    else:
        from ._mac_detect import *
    del V
elif platform.release() == "2012ServerR2":
    from ._dummy import *
elif sys.platform == "win32" and int(platform.release()) >= 10:
    # Checks if running Windows 10 version 10.0.14393 (Anniversary Update) OR HIGHER. The getwindowsversion method returns a tuple.
    # The third item is the build number that we can use to check if the user has a new enough version of Windows.
    winver = int(platform.version().split('.')[2])
    if winver >= 14393:
        from ._windows_detect import *
    else:
        from ._dummy import *
elif sys.platform == "linux":
    from ._linux_detect import *
else:
    from ._dummy import *

del sys, platform
```

**Comment by psobolewskiPhD** [comment]
I *think* this has been solved in the latest `darkdetect`
https://github.com/albertosottile/darkdetect/pull/21/files
So I assume this napari PR: https://github.com/napari/napari/pull/4508 fixes the issue. It's on the 0.4.16 milestone, so the next napari release 0.4.16 should fix it.
I think you can test using a release candidate:
`pip install -pre napari -U`

**Comment by MalteMederacke** [comment]
Does not work for me. I have napery 0.4.16 and still get the error:

ValueError: invalid literal for int() with base 10: '2012ServerR2'

**Comment by psobolewskiPhD** [comment]
Hmm, looks like even though the PR was merged (https://github.com/napari/napari/pull/4561) and had the 0.4.16 milestone, it didn't make it to 0.4.16 release. I can confirm that on live 0.4.16 I have `__version__ = '0.5.2'`

I don't really understand how vendors stuff works. 
@Carreau any idea if manually installing `darkdetect` 0.6.0 would fix the issue?

**Comment by goanpeca** [comment]
>any idea if manually installing darkdetect 0.6.0 would fix the issue?

Unfortunately It will not work since we import from the vendor folder.

**Comment by kevinyamauchi** [comment]
Thanks for looking into this @psobolewskiPhD and @goanpeca ! Indeed it looks like we missed #4561 in 0.4.16.

https://github.com/napari/napari/blob/36c94477b5b63e160f75cf8c4aef5524e2a6af19/napari/_vendor/darkdetect/__init__.py#L7

@MalteMederacke , sorry about that. As @psobolewskiPhD said, it looks like #4561 is merged in `main` and it _should_ fix your issue. You can try to upgrade from `main` with

```bash
pip install --upgrade "git+https://github.com/napari/napari.git#egg=napari[all]"
```

**Comment by kevinyamauchi** [comment]
I am going to close this as resolved as it current works on `main` for me. I will ping the 0.4.17 release managers to make sure that the fix is included.

Please feel free to reopen if the issue is not resolved for you on `main`.
