### ISSUE TITLE
After moving or rotating shapes, they sometimes stop interacting correctly.

### ISSUE THREAD

**Issue by TimMonko** [napari/napari#7344]
### 🐛 Bug Report

After drawing on a shape, and then moving/rotating the image, it stops being interacted with correctly. A few things I've noticed:
1. The shape might not be able to be reselected
2. The shape might be able to be rotated but not moved
3. *Maybe* rotating the shape again allows the shape to be moved (first gif)
4. *Maybe* doing a 'drag' highlight of the shape reintroduces interactivity. (first gif)
5. When all movement interactivity can't be recovered, resizing the shape allows movement again (second gif) 

This all usually happens without an Error. But, I noticed that when trying to troubleshoot the cause enough times, it eventually triggers an error, pasted into 'Additional Context'. (yay this is probably insight!) 

![python_kk1lw83TpN](https://github.com/user-attachments/assets/4bf6f4cc-034a-4598-8ff8-f8be39fa07c1)

![python_7VVWhimRoh](https://github.com/user-attachments/assets/41e2f481-d22b-47da-9a0a-d5a843bd8112)

### 💡 Steps to Reproduce

1. Add a Shapes Layer
2. Draw a rectangle or polygon shape (perhaps this happens with others, untested)
3. Switch to 'Select Shapes'
4. My frequent use case is to move and rotate a shape into a specific place on the image.

### 💡 Expected Behavior

Shape interactivity proceeds as expected. 

### 🌎 Environment

napari: 0.5.4
Platform: Windows-10-10.0.22631-SP0
Python: 3.10.15 | packaged by conda-forge | (main, Sep 30 2024, 17:41:41) [MSC v.1941 64 bit (AMD64)]
Qt: 5.15.2
PyQt5: 5.15.11
NumPy: 1.26.4
SciPy: 1.14.1
Dask: 2024.9.1
VisPy: 0.14.3
magicgui: 0.9.1
superqt: 0.6.7
in-n-out: 0.2.1
app-model: 0.3.0
psygnal: 0.11.1
npe2: 0.7.7
pydantic: 2.9.2

OpenGL:
- GL version: 4.6.0 NVIDIA 551.78
- MAX_TEXTURE_SIZE: 32768
- GL_MAX_3D_TEXTURE_SIZE: 16384

Screens:
- screen 1: resolution 1920x1080, scale 2.0
- screen 2: resolution 1440x2560, scale 1.0

Optional:
- numba: 0.60.0
- triangle: 20230923
- napari-plugin-manager: 0.1.3

Settings path:
- C:\Users\timmo\AppData\Local\napari\ndev-311_38088f5b898b2da4d541680bbce088d4fc867539\settings.yaml

### 💡 Additional Context

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\_qt\threads\status_checker.py:100, in StatusChecker.calculate_status(self=<napari._qt.threads.status_checker.StatusChecker object>)
     97     return
     99 try:
--> 100     res = viewer._calc_status_from_cursor()
        viewer = Viewer(camera=Camera(center=(0.0, 255.5, 255.5), zoom=0.7361572265625, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=False, mouse_zoom=True), cursor=Cursor(position=(182.8253067101062, 314.59063472594073), scaled=True, style=<CursorStyle.POINTING: 'pointing'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), rollable=(True, True), range=(RangeTuple(start=80.76846922386913, stop=302.54141496135145, step=1.0), RangeTuple(start=190.05961369400924, stop=430.9712230970993, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(191.76846922386915, 253.05961369400924), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Shapes layer 'Shapes' at 0x1ccb84a98d0>], help='use <6> for pan/zoom, use <7> for transform, use <R> for add rectangles, use <E> for add ellipses, use <L> for add lines, use <T> for add path, use <P> for add polygons, use <Shift+P> for add polygons lasso, use <4> for select vertices, use <2> for insert vertex, use <1> for remove vertex', status={'layer_name': 'Shapes', 'layer_base': 'Shapes', 'source_type': '', 'plugin': '', 'coordinates': ' [192 268]: [, ]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001CC97F353F0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
    101 except Exception as e:  # pragma: no cover # noqa: BLE001
    102     # Our codebase is not threadsafe. It is possible that an
    103     # ViewerModel or Layer state is changed while we are trying to
   (...)
    107     #
    108     # We do not want to crash the thread to keep the status updates.
    109     notification_manager.dispatch(Notification.from_exception(e))

File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\components\viewer_model.py:564, in ViewerModel._calc_status_from_cursor(self=Viewer(camera=Camera(center=(0.0, 255.5, 255.5),...use_drag_gen={}, _mouse_wheel_gen={}, _keymap={}))
    562 active = self.layers.selection.active
    563 if active is not None:
--> 564     status = active.get_status(
        active = <Shapes layer 'Shapes' at 0x1ccb84a98d0>
        self = Viewer(camera=Camera(center=(0.0, 255.5, 255.5), zoom=0.7361572265625, angles=(0.0, 0.0, 90.0), perspective=0.0, mouse_pan=False, mouse_zoom=True), cursor=Cursor(position=(182.8253067101062, 314.59063472594073), scaled=True, style=<CursorStyle.POINTING: 'pointing'>, size=1.0), dims=Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), rollable=(True, True), range=(RangeTuple(start=80.76846922386913, stop=302.54141496135145, step=1.0), RangeTuple(start=190.05961369400924, stop=430.9712230970993, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(191.76846922386915, 253.05961369400924), last_used=0), grid=GridCanvas(stride=1, shape=(-1, -1), enabled=False), layers=[<Shapes layer 'Shapes' at 0x1ccb84a98d0>], help='use <6> for pan/zoom, use <7> for transform, use <R> for add rectangles, use <E> for add ellipses, use <L> for add lines, use <T> for add path, use <P> for add polygons, use <Shift+P> for add polygons lasso, use <4> for select vertices, use <2> for insert vertex, use <1> for remove vertex', status={'layer_name': 'Shapes', 'layer_base': 'Shapes', 'source_type': '', 'plugin': '', 'coordinates': ' [192 268]: [, ]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x000001CC97F353F0>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, _keymap={})
        self.cursor.position = (182.8253067101062, 314.59063472594073)
        self.cursor = Cursor(position=(182.8253067101062, 314.59063472594073), scaled=True, style=<CursorStyle.POINTING: 'pointing'>, size=1.0)
        self.cursor._view_direction = None
        self.dims = Dims(ndim=2, ndisplay=2, order=(0, 1), axis_labels=('0', '1'), rollable=(True, True), range=(RangeTuple(start=80.76846922386913, stop=302.54141496135145, step=1.0), RangeTuple(start=190.05961369400924, stop=430.9712230970993, step=1.0)), margin_left=(0.0, 0.0), margin_right=(0.0, 0.0), point=(191.76846922386915, 253.05961369400924), last_used=0)
    565         self.cursor.position,
    566         view_direction=self.cursor._view_direction,
    567         dims_displayed=list(self.dims.displayed),
    568         world=True,
    569     )
    571     if self.tooltip.visible:
    572         tooltip_text = active._get_tooltip_text(
    573             np.asarray(self.cursor.position),
    574             view_direction=np.asarray(self.cursor._view_direction),
    575             dims_displayed=list(self.dims.displayed),
    576             world=True,
    577         )

File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\layers\base\base.py:2137, in Layer.get_status(self=<Shapes layer 'Shapes'>, position=array([197.76777, 273.83847]), view_direction=None, dims_displayed=[0, 1], world=True)
   2135 if position is not None:
   2136     position = np.asarray(position)
-> 2137     value = self.get_value(
        self = <Shapes layer 'Shapes' at 0x1ccb84a98d0>
        position = array([197.76777, 273.83847])
        view_direction = None
        dims_displayed = [0, 1]
        world = True
   2138         position,
   2139         view_direction=view_direction,
   2140         dims_displayed=dims_displayed,
   2141         world=world,
   2142     )
   2143 else:
   2144     value = None

File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\layers\base\base.py:1405, in Layer.get_value(self=<Shapes layer 'Shapes'>, position=array([197.76777, 273.83847]), view_direction=None, dims_displayed=[0, 1], world=True)
   1399             value = self._get_value_3d(
   1400                 start_point=start_point,
   1401                 end_point=end_point,
   1402                 dims_displayed=dims_displayed,
   1403             )
   1404     else:
-> 1405         value = self._get_value(position)
        position = array([197.76777, 273.83847])
        self = <Shapes layer 'Shapes' at 0x1ccb84a98d0>
   1407 else:
   1408     value = None

File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\layers\shapes\shapes.py:2838, in Shapes._get_value(self=<Shapes layer 'Shapes'>, position=array([197.76777, 273.83847]))
   2831 # Get the vertex sizes. They need to be rescaled by a few parameters:
   2832 # - scale_factor, because vertex sizes are zoom-invariant
   2833 # - scale, because vertex sizes are not affected by scale (unlike in Points)
   2834 # - 2, because the radius is what we need
   2836 if self._mode == Mode.SELECT:
   2837     # Check if inside vertex of interaction box or rotation handle
-> 2838     box = self._selected_box[Box.WITH_HANDLE]
        self = <Shapes layer 'Shapes' at 0x1ccb84a98d0>
        self._selected_box = None
        Box.WITH_HANDLE = [0, 1, 2, 3, 4, 5, 6, 7, 9]
   2839     distances = abs(box - coord)
   2841     # Check if any matching vertices

TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\_qt\threads\status_checker.py:86, in StatusChecker.run(self=<napari._qt.threads.status_checker.StatusChecker object>)
     84 if self._need_status_update.is_set():
     85     self._need_status_update.clear()
---> 86     self.calculate_status()
        self = <napari._qt.threads.status_checker.StatusChecker object at 0x000001CCA89E7520>
     87 else:
     88     self._need_status_update.wait()

File ~\mambaforge\envs\ndev-311\lib\site-packages\napari\_qt\threads\status_checker.py:110, in StatusChecker.calculate_status(self=<napari._qt.threads.status_checker.StatusChecker object>)
    101 except Exception as e:  # pragma: no cover # noqa: BLE001
    102     # Our codebase is not threadsafe. It is possible that an
    103     # ViewerModel or Layer state is changed while we are trying to
   (...)
    107     #
    108     # We do not want to crash the thread to keep the status updates.
    109     notification_manager.dispatch(Notification.from_exception(e))
--> 110 self.status_and_tooltip_changed.emit(res)
        self = <napari._qt.threads.status_checker.StatusChecker object at 0x000001CCA89E7520>

UnboundLocalError: local variable 'res' referenced before assignment
```

**Comment by Czaki** [comment]
Hi, @TimMonko. Thanks for reporting the error. It looks like the main error that you have reported is already fixed in #7332 (buts it's description may not help to search it). 


The `UnboundLocalError: local variable 'res' referenced before assignment` is solved by #7337. 

Unfortunately, both PR are unreleased yet. If you would like to check if it solves your problem, you need to install napari from the main branch of the repository. 


The `TypeError: 'NoneType' object is not subscriptable` error is something that I worried about when implementing #7146. When we have two threads. It looks like the main thread has changed the `selection` status during calculation of status. I will think about possible solution to reduce this problem.

**Comment by TimMonko** [comment]
> It looks like the main error that you have reported is already fixed in #7332 (buts it's description may not help to search it).

Yes, this looks to have solved the issue with interactivity.

> The `UnboundLocalError: local variable 'res' referenced before assignment` is solved by #7337.

Yes, a bit of playing appears that this is resolved.

> The `TypeError: 'NoneType' object is not subscriptable` error is something that I worried about when implementing #7146. When we have two threads. It looks like the main thread has changed the `selection` status during calculation of status. I will think about possible solution to reduce this problem.

I can confirm that I am still getting this error with both patches installed, as expected. But, it does not seem to cause me any issues (so far), just the warning.

**Comment by Czaki** [comment]
> I can confirm that I am still getting this error with both patches installed, as expected. But, it does not seem to cause me any issues (so far), just the warning.

@jni it looks like it will require to use some mechanism to solve thread racing (for example `Lock`). How did you think it is important?

**Comment by psobolewskiPhD** [comment]
Does 0.5.5 solve this on your end @TimMonko ? I can't reproduce with 0.5.5 on my mac.

**Comment by TimMonko** [comment]
I am unable to replicate: `TypeError: 'NoneType' object is not subscriptable` to confirm if this is solved (as there is no related PR)., but I can't trigger it on 0.5.5

As mentioned by @Czaki the interaction is fixed by #7332 and the `The UnboundLocalError: local variable 'res' referenced before assignment` is solved by #7337. I can confirm that these appear fixed on 0.5.5
